name: grgrie-inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.9.1+cpu
    - torchvision==0.24.1+cpu
    - onnxruntime==1.23.2
    - ultralytics==8.3.231
    - fastapi
    - uvicorn
    - selenium
    - webdriver-manager
    - fitz
    - PyMuPDF
    - python-multipart
    - jinja2
    - opencv-python-headless==4.11.0.86
    - pillow
    - numpy==1.26.4
    - paddlepaddle==2.6.2
    - paddleocr==2.9.1
    - python-telegram-bot
    - python-dotenv
    - requests
    - pyyaml
